### ISSUE TITLE
Argument depth doesn't work

### ISSUE THREAD

**Issue by ananastii** [lizaku/vec2graph#1]
Always one page for the query token is generated
No alerts with depth=-0.5 (depth must be integer and positive.

**Comment by ananastii** [comment]
The problem is in the function  `get_neighbors`:
https://github.com/lizaku/vec2graph/blob/ddb851f414cde90f6ba33c1ea1c595d302de4d47/vec2graph/genviz.py#L33

In the first version it took `datum` (there all nodes are stored) as argument and recursively added new nodes in it. Now it creates new data, and didn't update `datum`, so it will always contained only info for first parent node ( and produce page for just this node, whatever the value of depth).

The first version looked like:
```def get_neighbors(model, datum, stack, depth, topn):
    if depth > 0:
        depth -= 1
        for neighbor in stack:
            res = get_most_similar(model, neighbor, topn)
            datum[neighbor] = res[0]
            get_neighbors(model, datum, res[1], depth, topn)
    return```

What was the reason to rewrite this? Which new features I should save during the fixing?

**Comment by akutuzov** [comment]
@lizaku Do you have anything to say here?
